# Generated by Django 6.0.6 on 2026-06-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='html_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
