# Generated by Django 6.0.6 on 2026-06-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('banner', models.ImageField(upload_to='deals/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='deals/thumbnails/')),
                ('deal_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('bogo', 'Buy One Get One'), ('combo', 'Combo Deal'), ('free_delivery', 'Free Delivery')], max_length=20)),
                ('coupon_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buy_quantity', models.PositiveIntegerField(default=1)),
                ('get_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(default=0)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_flash_sale', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('is_new_customer_only', models.BooleanField(default=False)),
                ('free_delivery', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('background_color', models.CharField(blank=True, max_length=20)),
                ('text_color', models.CharField(blank=True, max_length=20)),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='deals', to='menu.category')),
                ('products', models.ManyToManyField(blank=True, related_name='deals', to='menu.product')),
            ],
            options={
                'ordering': ['-priority', '-is_featured', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deals.deal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['coupon_code'], name='deals_deal_coupon__dd1e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['is_active'], name='deals_deal_is_acti_b6ead4_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['deal_type'], name='deals_deal_deal_ty_0b9ede_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['start_date', 'end_date'], name='deals_deal_start_d_20cfdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dealitem',
            unique_together={('deal', 'product')},
        ),
    ]
