# Generated by Django 6.0.6 on 2026-06-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_total_price_cartitemaddon_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customization_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
