# Generated by Django 6.0.6 on 2026-06-22 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_customization_data_and_more'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='deal_discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
