# Generated by Django 6.0.6 on 2026-06-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_deal_cartitem_deal_discount_percent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
