# Generated by Django 6.0.6 on 2026-06-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
